project:
  type: website
  output-dir: docs

website:
  title: "The 1000 Watch Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: average_prices.qmd
        text: Average Prices
      - href: chronograph_vs_diver.qmd
        text: Chronographs vs. Divers
      - href: watch_landscape.qmd
        text: Watch Landscape
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
